spring.application.name=Cinema-Ebooking-Site
spring.mongodb.uri=mongodb+srv://laurenlindsey0903_db_user:Cinema123@cinema-ebooking.ingct7j.mongodb.net/?appName=cinema-ebooking
spring.mongodb.database=moviedb
server.port=8080