spring.application.name=Cinema-Ebooking-Site
spring.data.mongodb.uri=mongodb+srv://laurenlindsey0903_db_user:Cinema123@cinema-ebooking.ingct7j.mongodb.net/movie_db?retryWrites=true&w=majority&appName=cinema-ebooking
server.port=8080