spring.datasource.url=jdbc:mysql://cinema-dev-db.ctuacyycgzon.us-east-2.rds.amazonaws.com:3306/cinema-dev-db?useSSL=true&requireSSL=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=a48U5UAnpCgzjP3hZdso
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=team8cesebooking@gmail.com
spring.mail.password=brlsgylvamxeolff 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true